image: php:8.1

before_script:
    # Install some stuff that the image doesn't come with
    - apt update -yqq
    - apt install git libpq-dev libzip-dev zip make wget gnupg -yqq

    # Install phab
    - apt install phpab

    # Install the latest version of ncc (Nosial Code Compiler)
    - git clone https://git.n64.cc/nosial/ncc.git
    - cd ncc
    - make redist
    - php build/src/INSTALL --auto --install-composer
    - cd .. && rm -rf ncc

build:
    script:
        - ncc build --config release --log-level debug
    artifacts:
        paths:
        - build/
    rules:
        - if: $CI_COMMIT_BRANCH

release:
  stage: deploy
  script:
    - ncc build --config release --log-level debug
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/release/net.nosial.configlib.ncc "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/net.nosial.configlib/$CI_COMMIT_REF_NAME/net.nosial.configlib.ncc"
  artifacts:
    paths:
      - build/
  rules:
    - if: $CI_COMMIT_TAG
